# fly.toml app configuration file generated for syukurin on 2023-08-01T12:33:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "syukurin"
primary_region = "sin"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
